# -*- coding: utf-8 -*-
"""Labsession.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmhlCXvsjjrHCrFTW10Wz1DCX-5smnme
"""

try:

 std_name = str(input("Enter student name: "))
 classes_Held = int(input("Enter number of classes held: "))
 classes_attended = int(input("Enter number of classes attended: "))

 attendence_percentage = (classes_Held / classes_attended) * 100

 if attendence_percentage >= 75:
    print("Student is allowed to sit in exam")
    print("Attendence percentage is: ", attendence_percentage)
 else:
    print("Student is not allowed to sit in exam")
    print("Attendence percentage is: ", attendence_percentage)

except ValueError:
    print("Invalid input. Please enter valid numbers.")